import { useLanguage, type Lang } from "../i18n";

// ─── Türkçe (varsayılan)
const ALLERGEN_MAP_TR: Record<string, string> = {
    "A":  "Gluten içeren tahıllar",
    "Aa": "Buğday",
    "Ab": "Spelt",
    "Ac": "Çavdar",
    "Ad": "Arpa",
    "Ae": "Yulaf",
    "Af": "Kamut",
    "B":  "Kabuklular",
    "C":  "Yumurta",
    "D":  "Balık",
    "E":  "Yer fıstığı",
    "F":  "Soya fasulyesi",
    "G":  "Süt (Laktoz)",
    "H":  "Kabuklu yemişler (Badem, fındık, ceviz)",
    "I":  "Kereviz",
    "J":  "Hardal",
    "K":  "Kükürt dioksit / Sülfitler",
    "L":  "Kükürt dioksit ve sülfitler",
    "M":  "Lupin",
    "N":  "Susam tohumu",
    "Q":  "Lupin (baklagil türü)",
    "T":  "Yumuşakçalar (midye vb.)",
    "O":  "Susam",
    "1":  "Renklendirici içerir",
    "2":  "Koruyucu madde içerir",
    "3":  "Antioksidan içerir",
    "4":  "Tatlandırıcı içerir",
    "5":  "Kükürt ile işlenmiştir",
    "6":  "Karartılmıştır",
    "7":  "Fosfat içerir",
    "8":  "Süt proteini içerir",
    "9":  "Kafein içerir",
    "10": "Kinin içerir",
    "11": "Tatlandırıcı içerir",
    "12": "Fenilalanin kaynağı içerir",
    "13": "Mumlanmıştır",
    "14": "Taurin içerir",
    "15": "Nitritli tuz içerir",
};

// ─── Almanca
const ALLERGEN_MAP_DE: Record<string, string> = {
    "A":  "Glutenhaltiges Getreide",
    "Aa": "Weizen",
    "Ab": "Dinkel",
    "Ac": "Roggen",
    "Ad": "Gerste",
    "Ae": "Hafer",
    "Af": "Kamut",
    "B":  "Krebstiere",
    "C":  "Eier",
    "D":  "Fisch",
    "E":  "Erdnüsse",
    "F":  "Sojabohnen",
    "G":  "Milch (Laktose)",
    "H":  "Schalenfrüchte (Mandeln, Haselnüsse, Walnüsse)",
    "I":  "Sellerie",
    "J":  "Senf",
    "K":  "Schwefeldioxid / Sulfite",
    "L":  "Schwefeldioxid und Sulfite",
    "M":  "Lupinen",
    "N":  "Sesamsamen",
    "Q":  "Lupinen (Hülsenfrucht)",
    "T":  "Weichtiere (Muscheln usw.)",
    "O":  "Sesam",
    "1":  "Enthält Farbstoff",
    "2":  "Enthält Konservierungsstoff",
    "3":  "Enthält Antioxidationsmittel",
    "4":  "Enthält Süßungsmittel",
    "5":  "Mit Schwefel behandelt",
    "6":  "Geschwärzt",
    "7":  "Enthält Phosphat",
    "8":  "Enthält Milcheiweiß",
    "9":  "Enthält Koffein",
    "10": "Enthält Chinin",
    "11": "Enthält Süßungsmittel",
    "12": "Enthält eine Phenylalaninquelle",
    "13": "Gewachst",
    "14": "Enthält Taurin",
    "15": "Enthält Nitritpökelsalz",
};

// ─── İngilizce
const ALLERGEN_MAP_EN: Record<string, string> = {
    "A":  "Gluten-containing cereals",
    "Aa": "Wheat",
    "Ab": "Spelt",
    "Ac": "Rye",
    "Ad": "Barley",
    "Ae": "Oats",
    "Af": "Kamut",
    "B":  "Crustaceans",
    "C":  "Eggs",
    "D":  "Fish",
    "E":  "Peanuts",
    "F":  "Soybeans",
    "G":  "Milk (Lactose)",
    "H":  "Tree nuts (Almonds, hazelnuts, walnuts)",
    "I":  "Celery",
    "J":  "Mustard",
    "K":  "Sulphur dioxide / Sulphites",
    "L":  "Sulphur dioxide and sulphites",
    "M":  "Lupin",
    "N":  "Sesame seeds",
    "Q":  "Lupin (legume)",
    "T":  "Molluscs (mussels etc.)",
    "O":  "Sesame",
    "1":  "Contains colouring",
    "2":  "Contains preservative",
    "3":  "Contains antioxidant",
    "4":  "Contains sweetener",
    "5":  "Treated with sulphur",
    "6":  "Blackened",
    "7":  "Contains phosphate",
    "8":  "Contains milk protein",
    "9":  "Contains caffeine",
    "10": "Contains quinine",
    "11": "Contains sweetener",
    "12": "Contains a source of phenylalanine",
    "13": "Waxed",
    "14": "Contains taurine",
    "15": "Contains nitrite curing salt",
};

// ─── Rusça
const ALLERGEN_MAP_RU: Record<string, string> = {
    "A":  "Злаки, содержащие глютен",
    "Aa": "Пшеница",
    "Ab": "Спельта",
    "Ac": "Рожь",
    "Ad": "Ячмень",
    "Ae": "Овёс",
    "Af": "Камут",
    "B":  "Ракообразные",
    "C":  "Яйца",
    "D":  "Рыба",
    "E":  "Арахис",
    "F":  "Соевые бобы",
    "G":  "Молоко (Лактоза)",
    "H":  "Орехи (Миндаль, фундук, грецкий орех)",
    "I":  "Сельдерей",
    "J":  "Горчица",
    "K":  "Диоксид серы / Сульфиты",
    "L":  "Диоксид серы и сульфиты",
    "M":  "Люпин",
    "N":  "Семена кунжута",
    "Q":  "Люпин (бобовое растение)",
    "T":  "Моллюски (мидии и т.д.)",
    "O":  "Кунжут",
    "1":  "Содержит краситель",
    "2":  "Содержит консервант",
    "3":  "Содержит антиоксидант",
    "4":  "Содержит подсластитель",
    "5":  "Обработано серой",
    "6":  "Почернено",
    "7":  "Содержит фосфат",
    "8":  "Содержит молочный белок",
    "9":  "Содержит кофеин",
    "10": "Содержит хинин",
    "11": "Содержит подсластитель",
    "12": "Содержит источник фенилаланина",
    "13": "Покрыто воском",
    "14": "Содержит таурин",
    "15": "Содержит нитритную соль",
};

// ─── Map by language
const ALLERGEN_MAPS: Record<Lang, Record<string, string>> = {
    tr: ALLERGEN_MAP_TR,
    de: ALLERGEN_MAP_DE,
    en: ALLERGEN_MAP_EN,
    ru: ALLERGEN_MAP_RU,
};

// ─── Hook: kullanım → const allergenMap = useAllergenMap() ───────────────────
export function useAllergenMap(): Record<string, string> {
    const { lang } = useLanguage();
    return ALLERGEN_MAPS[lang] ?? ALLERGEN_MAP_TR;
}